### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [BioImaging-NKI/Visualising-homology-search-in-human-cells#1]
Hi @bvandenbroek ,

that's a fantastic repository! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by BioImaging-NKI** [comment]
Hi @haesleinhuepf,

Thanks! 😄 This repository contains a few scripts that we used in a paper that is yet to be submitted. Good point about the license. I think GPLv3 makes the most sense, so I added the file.

All the best,
Bram
